'use client';
import {useEffect,useState,lazy,Suspense,Fragment} from 'react';
import {Check,ChevronRight,Code2,Play,RotateCcw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {VisualLesson} from './visual-lesson';
import {pythonLessons,algorithmLessons,type CourseLesson} from '@/data/course-lessons';
import exerciseData from '@/data/course-exercises.json';
import type {Problem} from './practice-workspace';
const ProjectIDE=lazy(()=>import('./project-ide').then(m=>({default:m.ProjectIDE})));
type Exercise=(typeof exerciseData)[number];
const progressKey='usaco-course-exercise-progress-v1';
function FoundationDiagram({lesson}:{lesson:CourseLesson}){
 const [step,setStep]=useState(0);const frames=lesson.frames!;const frame=frames[step];
 return <div className="foundation-diagram"><div className="foundation-stages" aria-label="执行步骤">{frames.map((f,i)=><button key={f.label} aria-current={i===step?'step':undefined} onClick={()=>setStep(i)}><span>{i+1}</span>{f.label}{i<frames.length-1&&<ChevronRight size={15}/>}</button>)}</div><div className="foundation-frame" aria-live="polite"><small>第 {step+1} 步 · {frame.label}</small><pre>{frame.value}</pre><p>{frame.explanation}</p></div><div className="foundation-controls"><span>二维执行演示</span><Button variant="ghost" onClick={()=>setStep(0)}><RotateCcw size={14}/>重置</Button><Button variant="outline" onClick={()=>setStep(s=>Math.min(frames.length-1,s+1))} disabled={step===frames.length-1}><Play size={14}/>下一步</Button></div></div>;
}
function ExercisePanel({exercise,onPassed}:{exercise:Exercise;onPassed:()=>void}){
 const [coding,setCoding]=useState(false),[help,setHelp]=useState(false),[reference,setReference]=useState(false);
 const p:Problem={id:exercise.id,title:exercise.title,zhTitle:exercise.title,roundLabel:'课堂练习',year:2026,season:'course',tags:[],reviewStatus:'教学练习',level:'Bronze',visual:'',official:'',editorial:'',testsUrl:'',summary:exercise.prompt,summaryEn:'',analysis:'',hints:[exercise.hint],samples:[exercise.cases[0]],io:'stdin',checker:'tokens',testsImported:exercise.cases.length,testsTotal:exercise.cases.length};
 return <div className="course-exercise"><h3>{exercise.title}</h3><p>{exercise.prompt}</p><div className="exercise-formats"><section><h4>输入格式</h4><p>{exercise.inputFormat}</p></section><section><h4>输出格式</h4><p>{exercise.outputFormat}</p></section></div><div className="sample-columns"><div><label>Sample Input</label><pre>{exercise.cases[0].input}</pre></div><div><label>Sample Output</label><pre>{exercise.cases[0].output}</pre></div></div><div className="exercise-actions"><Button onClick={()=>setCoding(true)} disabled={coding}><Code2 size={15}/>{coding?'编程区已打开':'开始练习'}</Button><Button variant="ghost" onClick={()=>setHelp(!help)} aria-expanded={help}>思路提示</Button><Button variant="ghost" onClick={()=>setReference(!reference)} aria-expanded={reference}>参考解法</Button><span>{exercise.cases.length} 组测试 · Python 3</span></div>{help&&<p className="exercise-hint">{exercise.hint}</p>}{reference&&<pre className="code-sample">{exercise.solution}</pre>}{coding&&<Suspense fallback={<p>正在打开编辑器…</p>}><ProjectIDE problem={p} mode="learning" onAttempt={()=>{}} practiceCases={exercise.cases} onGraded={passed=>{if(passed)onPassed();}}/></Suspense>}</div>;
}
function LessonPractice({lesson,onComplete}:{lesson:CourseLesson;onComplete:()=>void}){
 const exercises=exerciseData.filter(e=>e.lesson===lesson.id);const [selected,setSelected]=useState(0),[passed,setPassed]=useState<number[]>([]);
 useEffect(()=>{try{const values=JSON.parse(localStorage.getItem(progressKey)||'[]');if(Array.isArray(values))setPassed(values.filter(Number.isInteger));}catch{}},[]);
 function markPassed(id:number){let saved:number[]=[];try{const value=JSON.parse(localStorage.getItem(progressKey)||'[]');if(Array.isArray(value))saved=value.filter(Number.isInteger);}catch{}const next=[...new Set([...saved,...passed,id])];setPassed(next);try{localStorage.setItem(progressKey,JSON.stringify(next));}catch{}if(exercises.every(e=>next.includes(e.id)))onComplete();}
 return <section className="lesson-practice"><div className="section-heading"><div><p className="eyebrow">PRACTICE</p><h2>把刚学的知识写成代码</h2></div><span className="course-progress">{exercises.filter(e=>passed.includes(e.id)).length} / 3 已通过</span></div><p className="muted-copy">依次完成基础、巩固与挑战。运行样例后，用“检查全部”检验边界情况。</p><div className="exercise-levels" role="tablist" aria-label="练习难度">{exercises.map((e,i)=><button key={e.id} role="tab" aria-selected={i===selected} aria-controls={`exercise-${lesson.id}`} onClick={()=>setSelected(i)}><span>{passed.includes(e.id)?<Check size={16}/>:String(i+1).padStart(2,'0')}</span><div><small>{e.level}</small>{e.title}</div></button>)}</div><div id={`exercise-${lesson.id}`} role="tabpanel"><ExercisePanel key={exercises[selected].id} exercise={exercises[selected]} onPassed={()=>markPassed(exercises[selected].id)}/></div></section>;
}
export function CoursePage({section,selected,onSelect,onOpenProblem,onLessonDone,done}:{section:'python'|'algorithm';selected:string;onSelect:(id:string)=>void;onOpenProblem:(id:number)=>void;onLessonDone:(id:string)=>void;done:string[]}){
 const list=section==='python'?pythonLessons:algorithmLessons,lesson=list.find(l=>l.id===selected)||list[0],index=list.findIndex(l=>l.id===lesson.id);
 return <><div className="page-title"><div><p className="eyebrow">{section==='python'?'PYTHON FOUNDATIONS':'ALGORITHM CLASSROOM'}</p><h1>{section==='python'?'先把 Python 用顺手。':'看见过程，再独立实现。'}</h1><p>{section==='python'?'只学竞赛需要的基础：输入输出、条件循环、常用数据结构与函数。':'用图解理解原理，再通过三道递进练习巩固，最后迁移到真题。'}</p></div><span className="course-progress">{list.filter(l=>done.includes(l.id)).length} / {list.length} 节完成</span></div>{section==='algorithm'&&<div className="curriculum-note"><strong>先学方法，再练迁移</strong><span>6 节基础方法 · 6 节思维专题 · 4 节近年题型 · 2 节进阶衔接。分类并不是封闭考纲；遇到新题，仍需观察、验证与证明。</span></div>}<div className="classroom-layout"><aside className="lesson-list" aria-label={section==='python'?'Python 基础课程':'算法课程'}>{list.map((l,i)=><Fragment key={l.id}>{section==='algorithm'&&(i===0||l.group!==list[i-1].group)&&<h3 className="lesson-group-label">{l.group}</h3>}<button className={l.id===lesson.id?'active':''} key={l.id} onClick={()=>onSelect(l.id)} aria-current={l.id===lesson.id?'page':undefined}><span>{done.includes(l.id)?<Check size={15}/>:String(i+1).padStart(2,'0')}</span><div>{l.title}<small>{l.minutes} 分钟 · 3 道练习</small></div></button></Fragment>)}</aside><article className="lesson-content"><div className="lesson-heading"><span className="badge">{section==='python'?'Python 基础':lesson.label}</span><h2>{lesson.title}</h2><p>{lesson.desc}</p></div>{lesson.kind?<VisualLesson key={'visual-'+lesson.id} kind={lesson.kind} steps={lesson.steps} lessonId={lesson.id}/>:<FoundationDiagram key={'visual-'+lesson.id} lesson={lesson}/>}<div className="course-explanation"><section><h3>这一课要掌握</h3><ul>{lesson.notes.map(note=><li key={note}>{note}</li>)}</ul></section><section><h3>对应代码 / 伪代码</h3><pre className="code-sample">{lesson.code}</pre></section></div><LessonPractice key={'practice-'+lesson.id} lesson={lesson} onComplete={()=>onLessonDone(lesson.id)}/><div className="course-next">{lesson.problem&&<Button variant="outline" onClick={()=>onOpenProblem(lesson.problem!)}>练对应真题</Button>}<Button onClick={()=>onSelect(index<list.length-1?list[index+1].id:section==='python'?'complexity':'exam')}>{index<list.length-1?'下一课：'+list[index+1].title:section==='python'?'进入算法课堂':'进入模拟考试'}<ChevronRight size={15}/></Button></div></article></div></>;
}
