'use client';
import {useEffect,useState,useRef,lazy,Suspense} from 'react';
import {Code2,BookOpen,Columns2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Textarea} from '@/components/ui/textarea';
import {Collapsible,CollapsibleTrigger,CollapsibleContent} from '@/components/ui/collapsible';
import {ResizablePanelGroup,ResizablePanel,ResizableHandle} from '@/components/ui/resizable';
import type {PanelImperativeHandle} from 'react-resizable-panels';
import {ProblemDiagram} from './problem-diagram';
import {ReferencePanel} from './reference-panel';
import {OfficialStatement} from './official-statement';
const ProjectIDE=lazy(()=>import('./project-ide').then(m=>({default:m.ProjectIDE})));
export type Problem={id:number,title:string,zhTitle:string,roundLabel:string,year:number,season:string,tags:string[],reviewStatus:string,level:string,visual:string,official:string,editorial:string,testsUrl:string,summary:string,summaryEn:string,analysis:string,hints:string[],samples:{input:string,output:string}[],inputFile?:string|null,io:string,checker:string,testsImported:number,testsTotal:number,alternativeSource?:string,languageNote?:string;learningTopics?:string[];optionalTopics?:string[];practiceStage?:string;classificationBasis?:string;statementAvailable?:boolean};
export type Attempt={id:number,title:string,date:string,status:string,detail:string};
export function Choice({value,onChange,options,label}:{value:string,onChange:(v:string)=>void,options:{value:string,label:string}[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export default function PracticeWorkspace({problem:p,mode,setMode,onAttempt,examExpired=false}:{problem:Problem,mode:string,setMode:(v:string)=>void,onAttempt:(a:Attempt)=>void,examExpired?:boolean}){
 const [layout,setLayout]=useState('read'),[ideStarted,setIdeStarted]=useState(false),[tab,setTab]=useState('task'),[summaryLanguage,setSummaryLanguage]=useState('zh'),[hint,setHint]=useState(0),[note,setNote]=useState(''),[compact,setCompact]=useState(false);
 const reading=useRef<PanelImperativeHandle|null>(null),coding=useRef<PanelImperativeHandle|null>(null),lastHint=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{setNote(localStorage.getItem(`usaco-note-${p.id}`)||'');const media=matchMedia('(max-width:1050px)');const update=()=>setCompact(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[p.id]);
 useEffect(()=>{if(mode==='exam'){setTab('task');setHint(0);}},[mode]);
 useEffect(()=>{if(layout==='read'){coding.current?.collapse();reading.current?.resize('100%');}else if(layout==='code'){reading.current?.collapse();coding.current?.resize('100%');}else{reading.current?.resize('48%');coding.current?.resize('52%');}},[layout,compact]);
 useEffect(()=>{if(tab==='guide'&&hint>0)lastHint.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[hint,tab]);
 function startCoding(){setIdeStarted(true);setLayout(compact?'code':'split');}
 function switchLayout(value:string){if(value!=='read')setIdeStarted(true);setLayout(value);}
 const shownHints=mode==='learning';
 return <section className={'workspace workspace-'+layout}><div className="work-header"><div><span className="micro">{p.roundLabel} · Bronze · #{p.id}</span><h1>{p.title}<small>{p.zhTitle!==p.title?p.zhTitle:''}</small></h1></div><div className="workspace-controls"><Choice value={mode} onChange={setMode} label="训练模式" options={[{value:'learning',label:'学习模式'},{value:'independent',label:'独立练习'},{value:'exam',label:'模考模式'}]}/>{!ideStarted?<Button onClick={startCoding}><Code2 size={15}/>开始编程</Button>:<Tabs value={layout} onValueChange={switchLayout}><TabsList aria-label="工作区布局"><TabsTrigger value="read"><BookOpen size={14}/>读题</TabsTrigger><TabsTrigger value="split"><Columns2 size={14}/>并排</TabsTrigger><TabsTrigger value="code"><Code2 size={14}/>编程</TabsTrigger></TabsList></Tabs>}</div></div>
 <ResizablePanelGroup orientation={compact?'vertical':'horizontal'} className="practice-panels"><ResizablePanel id={`reading-${p.id}`} panelRef={reading} className="practice-panel-inner" style={{height:'100%',minHeight:0,overflow:'hidden'}} defaultSize="100%" minSize="24%" collapsible collapsedSize="0%"><div className="reading-panel-scroll">
<article className="problem-panel"><Tabs value={tab} onValueChange={setTab}><TabsList variant="line"><TabsTrigger value="task">原题</TabsTrigger>{mode!=='exam'&&<TabsTrigger value="visual">样例图解</TabsTrigger>}{shownHints&&<TabsTrigger value="guide">解题引导</TabsTrigger>}{mode!=='exam'&&<TabsTrigger value="reference">参考代码</TabsTrigger>}{mode!=='exam'&&<TabsTrigger value="notes">我的笔记</TabsTrigger>}</TabsList>
 <TabsContent value="task" forceMount hidden={tab!=='task'}><OfficialStatement id={p.id} title={p.title} exam={mode==='exam'}/>
 {!p.statementAvailable&&<Collapsible defaultOpen className="sample-copy-section"><CollapsibleTrigger asChild><Button variant="ghost" size="sm">样例输入与输出</Button></CollapsibleTrigger><CollapsibleContent>{p.samples.map((s,i)=><div key={i} className="sample-block"><h3>样例 {i+1}</h3><div className="sample-columns"><div><label>Sample Input</label><pre>{s.input}</pre></div><div><label>Sample Output</label><pre>{s.output}</pre></div></div></div>)}</CollapsibleContent></Collapsible>}
 {mode!=='exam'&&<div className="reading-next"><span>读完题目后，打开编程区写下第一版解法。</span><div><Button onClick={startCoding}><Code2 size={15}/>开始编程</Button>{shownHints&&<Button variant="outline" onClick={()=>setTab('guide')}>需要解题帮助</Button>}<Button variant="ghost" onClick={()=>setTab('visual')}>查看样例图解</Button></div></div>}
 </TabsContent>
 <TabsContent value="visual"><ProblemDiagram id={p.id}/></TabsContent>
 <TabsContent value="reference"><ReferencePanel id={p.id}/></TabsContent>
 <TabsContent value="guide"><div className="guide-copy"><h3>整理题意，再逐步推导</h3><p>需要帮助时，先整理题意，再查看考点与提示。</p>
 <Collapsible defaultOpen className="guide-disclosure"><CollapsibleTrigger asChild><Button variant="outline">题意整理 · Summary</Button></CollapsibleTrigger><CollapsibleContent><div className="summary-tools"><span>教学辅助，不替代完整题面</span><Choice value={summaryLanguage} onChange={setSummaryLanguage} label="Summary 语言" options={[{value:'zh',label:'中文 Summary'},{value:'en',label:'English summary'}]}/></div><p className="statement">{summaryLanguage==='zh'?p.summary:p.summaryEn}</p></CollapsibleContent></Collapsible>
 <Collapsible defaultOpen className="guide-disclosure"><CollapsibleTrigger asChild><Button variant="outline">考点清单（含提示）</Button></CollapsibleTrigger><CollapsibleContent><div className="tag-row">{p.tags.length?p.tags.map(t=><span className="tag" key={t}>{t}</span>):<p>本题的考点归类仍待复核，可继续阅读下方解题提示。</p>}</div>{p.languageNote&&<p className="notice">{p.languageNote}</p>}{p.checker==='special'&&<p className="notice">本题校验方案是否满足题意，允许与官方示例不同的正确答案。</p>}</CollapsibleContent></Collapsible>
 <h3>逐层提示</h3>{p.hints.length?p.hints.slice(0,hint).map((s,i)=><div className="hint" ref={i===hint-1?lastHint:undefined} key={s}><span>提示 {i+1}</span><p>{s}</p></div>):<p>可在样例图解中观察任务，再到参考代码页查看完整思路与复杂度。</p>}{hint<p.hints.length&&<Button variant="outline" onClick={()=>setHint(hint+1)}>展开第 {hint+1} 层提示</Button>}{hint>=p.hints.length&&p.analysis&&<><h3>思路说明</h3><p>{p.analysis}</p><a href={p.editorial} target="_blank" rel="noreferrer">查看官方题解</a>{p.alternativeSource&&<p><a href={p.alternativeSource} target="_blank" rel="noreferrer">GitHub 可选解法依据</a></p>}</>}<div className="guide-practice-links"><Button variant="outline" onClick={()=>setTab('visual')}>样例图解</Button><Button variant="outline" onClick={()=>setTab('reference')}>Python 3 / C++ 参考代码</Button></div></div></TabsContent>
 <TabsContent value="notes"><h3>留下自己的思考</h3><p className="muted-copy">笔记保存在当前浏览器。建议写：卡在哪里、为什么错、下次如何识别。</p><Textarea rows={12} value={note} onChange={e=>{setNote(e.target.value);localStorage.setItem(`usaco-note-${p.id}`,e.target.value);}} placeholder="我最开始的想法是…"/></TabsContent></Tabs></article>
 </div></ResizablePanel><ResizableHandle withHandle disabled={layout!=='split'} className={layout==='split'?'practice-divider':'practice-divider hidden-divider'}/><ResizablePanel id={`coding-${p.id}`} panelRef={coding} className="practice-panel-inner" style={{height:'100%',minHeight:0,overflow:'hidden'}} defaultSize="0%" minSize="30%" collapsible collapsedSize="0%"><div className="coding-panel-scroll">{ideStarted&&<Suspense fallback={<p className="ide-opening">正在打开工作台…</p>}><ProjectIDE problem={p} mode={mode} onAttempt={onAttempt} examExpired={examExpired} visible={layout!=='read'}/></Suspense>}</div></ResizablePanel></ResizablePanelGroup>
 </section>;
}
