'use client';
import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Search,Library,Layers,Timer} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Pagination,PaginationContent,PaginationItem,PaginationLink,PaginationPrevious,PaginationNext} from '@/components/ui/pagination';
import {Empty} from '@/components/ui/empty';
import {Choice,type Problem} from './practice-workspace';
import topics from '@/data/learning-topics.json';
import {defaultArchiveFilters,filterProblems,inPeriod,topicMatches,stages,type ArchiveFilters,type ArchivePeriod} from '@/lib/problem-library';
export type LibraryRequest={topic:string;period:ArchivePeriod;nonce:number};
export function ProblemLibrary({problems,request,onOpen,onLesson,onRound}:{problems:Problem[];request?:LibraryRequest;onOpen:(id:number)=>void;onLesson:(id:string)=>void;onRound:(round:string)=>void}){
 const [filters,setFilters]=useState<ArchiveFilters>(defaultArchiveFilters),[view,setView]=useState('topics'),[page,setPage]=useState(1);
 useEffect(()=>{if(request){setFilters({...defaultArchiveFilters,period:request.period,topic:request.topic,order:'learning'});setView('topics');}},[request]);
 useEffect(()=>{setPage(1);},[filters,view]);
 const recent=problems.filter(p=>p.year>=2020),classic=problems.filter(p=>p.year<2020),querying=!!filters.query.trim(),period=querying?'all':filters.period;
 const topic=topics.find(t=>t.id===filters.topic);
 const filtered=useMemo(()=>filterProblems(problems,view==='rounds'?{...filters,topic:'all',stage:'all',order:'newest'}:filters),[problems,filters,view]);
 const rounds=[...new Set(filtered.map(p=>p.roundLabel))],years=[...new Set(problems.filter(p=>inPeriod(p,period)).map(p=>p.year))].sort((a,b)=>b-a);
 const size=view==='topics'?12:6,count=view==='topics'?filtered.length:rounds.length,totalPages=Math.max(1,Math.ceil(count/size)),safePage=Math.min(page,totalPages);
 const shown=filtered.slice((safePage-1)*size,safePage*size),shownRounds=rounds.slice((safePage-1)*size,safePage*size);
 function changePeriod(value:string){setFilters(f=>({...f,period:value as ArchivePeriod,query:'',year:'all'}));}
 function chooseTopic(id:string){setFilters(f=>({...f,topic:f.topic===id?'all':id,query:'',year:'all',stage:'all',order:'learning',period:f.period==='recent'&&!recent.some(p=>topicMatches(p,id))?'all':f.period}));}
 function reset(){setFilters(defaultArchiveFilters);setView('topics');}
 return <><div className="page-title archive-title"><div><p className="eyebrow">BRONZE PRACTICE</p><h1>铜组真题练习</h1><p>从 2020 年以来的 {recent.length} 道题开始；{classic.length} 道经典题用于补基础，也能在全库搜索中找到。</p></div><span className="archive-local-count"><BookOpen size={15}/>{recent.filter(p=>p.statementAvailable).length} 题中英全文</span></div>
 <div className="archive-mode-row"><Tabs value={view} onValueChange={setView}><TabsList variant="line" aria-label="选题方式"><TabsTrigger value="topics"><Layers size={15}/>按知识点练</TabsTrigger><TabsTrigger value="rounds"><Timer size={15}/>按场次练</TabsTrigger></TabsList></Tabs><div className="search-field"><Search size={16}/><Input value={filters.query} placeholder="搜索全部 99 题：题名或编号" aria-label="搜索全部题目" onChange={e=>{const query=e.target.value;setFilters(f=>({...f,query,...(query.trim()?{topic:'all',year:'all',stage:'all'}:{})}));}}/></div></div>
 <Tabs value={period} onValueChange={changePeriod} className="archive-periods"><TabsList aria-label="题目年份范围"><TabsTrigger value="recent">2020 年以来 <small>{recent.length}</small></TabsTrigger><TabsTrigger value="classic">2015–2019 经典 <small>{classic.length}</small></TabsTrigger><TabsTrigger value="all">全部题目 <small>{problems.length}</small></TabsTrigger></TabsList></Tabs>
 {view==='topics'&&<><div className="topic-directory" aria-label="全部知识点分类">{topics.map(t=>{const all=problems.filter(p=>topicMatches(p,t.id)),newer=all.filter(p=>p.year>=2020);return <Button key={t.id} variant="outline" className={filters.topic===t.id?'topic-choice active':'topic-choice'} aria-pressed={filters.topic===t.id} onClick={()=>chooseTopic(t.id)}><span>{t.label}</span><small>近年 {newer.length} · 全部 {all.length}</small></Button>;})}</div>{topic?<div className="archive-topic-guide"><div><b>{topic.label}</b><p>{topic.description}{topic.id==='dp'?' 本分类包含主解与可选拓展，题目中会分别标注。':''}</p></div>{topic.lesson&&<Button variant="outline" size="sm" onClick={()=>onLesson(topic.lesson!)}>复习先修课</Button>}<Button variant="ghost" size="sm" onClick={()=>setFilters(f=>({...f,topic:'all'}))}>全部分类</Button></div>:<p className="archive-reading-guide">选一个知识点，从基础巩固逐步进入综合挑战；准备检验独立解题能力时，切换到按场次练。</p>}</>}
 <div className="archive-filter-row"><div><Choice value={filters.year} onChange={year=>setFilters(f=>({...f,year}))} label="比赛年份" options={[{value:'all',label:'全部年份'},...years.map(y=>({value:String(y),label:`${y} 年`}))]}/>{view==='topics'&&<><Choice value={filters.stage} onChange={stage=>setFilters(f=>({...f,stage}))} label="练习阶段" options={[{value:'all',label:'全部阶段'},...stages.map(s=>({value:s,label:s}))]}/><Choice value={filters.order} onChange={order=>setFilters(f=>({...f,order}))} label="题目排序" options={[{value:'newest',label:'最新场次优先'},{value:'learning',label:'由基础到挑战'}]}/></>}</div><span>{querying?'全库搜索 · ':''}{view==='topics'?`${filtered.length} 道题`:`${rounds.length} 场 · 每场 3 题`}{period==='classic'?' · 经典题目前通过官网阅读':''}</span></div>
 {view==='topics'?<div className="problem-table archive-table"><Table><TableHeader><TableRow><TableHead>题目</TableHead><TableHead>场次</TableHead><TableHead>学习分类</TableHead><TableHead>练习阶段</TableHead><TableHead/></TableRow></TableHeader><TableBody>{shown.map(p=><TableRow key={p.id}><TableCell><button className="problem-name" onClick={()=>onOpen(p.id)}>{p.title}</button><div className="micro">#{p.id}{p.zhTitle!==p.title?' · '+p.zhTitle:''}</div><span className="library-resources">{p.statementAvailable?'中英题面 · 站内阅读':'经典题 · 官网阅读'} · {p.testsTotal} 组测试</span></TableCell><TableCell className="nowrap">{p.roundLabel}</TableCell><TableCell><div className="tag-row">{(p.learningTopics||[]).slice(0,3).map(id=><button className="tag archive-topic-tag" key={id} onClick={()=>chooseTopic(id)}>{topics.find(t=>t.id===id)?.label}</button>)}{p.optionalTopics?.includes('dp')&&<span className="tag optional-topic">DP · 可选拓展</span>}</div></TableCell><TableCell className="archive-stage">{p.practiceStage}</TableCell><TableCell><Button variant="outline" size="sm" onClick={()=>onOpen(p.id)}>读题</Button></TableCell></TableRow>)}</TableBody></Table></div>:<><p className="archive-reading-guide">按完整场次练习，不预先展示考点；进入计时训练后隐藏讲解和提示。</p><div className="round-directory">{shownRounds.map(round=>{const paper=problems.filter(p=>p.roundLabel===round).sort((a,b)=>a.id-b.id);return <article key={round} className="round-card"><header><div><h2>{round}</h2><p>Bronze · 常规赛 · 3 题</p></div><Button variant="outline" size="sm" onClick={()=>onRound(round)}>整场训练</Button></header><ol>{paper.map((p,i)=><li key={p.id}><span>{i+1}</span><button onClick={()=>onOpen(p.id)}>{p.title}</button><BookOpen size={14}/></li>)}</ol><small>{paper.every(p=>p.statementAvailable)?'中英题面均可站内阅读':'经典场次 · 官网题面'}</small></article>;})}</div></>}
 {!count&&<Empty className="empty-state"><Library size={28}/><h3>当前筛选下没有题目</h3><p>可以切换到全部年份，或清除筛选重新选择。</p><Button variant="outline" onClick={reset}>清除筛选</Button></Empty>}
 {totalPages>1&&<Pagination><PaginationContent><PaginationItem><PaginationPrevious href="#" aria-disabled={safePage===1} onClick={e=>{e.preventDefault();setPage(Math.max(1,safePage-1));}}/></PaginationItem>{Array.from({length:totalPages},(_,i)=><PaginationItem key={i}><PaginationLink href="#" isActive={safePage===i+1} onClick={e=>{e.preventDefault();setPage(i+1);}}>{i+1}</PaginationLink></PaginationItem>)}<PaginationItem><PaginationNext href="#" aria-disabled={safePage===totalPages} onClick={e=>{e.preventDefault();setPage(Math.min(totalPages,safePage+1));}}/></PaginationItem></PaginationContent></Pagination>}
 <p className="archive-classification-note">练习阶段与学习分类由本站按参考解法整理，不是官方难度评级。多标签题会出现在多个分类中；US Open 不在当前范围内。</p>
 </>;
}
