import json,re
from pathlib import Path
root=Path(__file__).resolve().parents[1]
r=json.loads((root/'data/catalog-raw.json').read_text())
# Original teaching summaries, written after reviewing official problem/editorial pages.
C={
567:('栅栏涂色',['区间与几何','模拟','分类讨论'],'入门','fence','FJ 给区间 [a,b] 涂色，Bessie 给 [c,d] 涂色。求至少被涂过一次的总长度。端点范围 0–100；a<b，c<d。长度按线段计算，不是端点个数。','Two painters cover intervals [a,b] and [c,d] on a fence. Calculate the length covered at least once. Endpoints are integers from 0 to 100, with a<b and c<d.','官方给出逐段标记与区间分类两种解法。也可用长度之和减去交集长度。',['先在数轴上标出四个端点。','重叠部分被两个人分别计算了几次？','交集长度是 max(0, min(b,d) − max(a,c))。']),
1589:('交换取胜',['构造','二维数组','计数'],'挑战','grid','有 N 个长度为 M 的字符串和目标 t。可以在同一行交换两个字符，或在同一列交换两行字符。请在不超过 2M 次操作内把第一行变成 t；输入保证有解。','Transform the first of N length-M strings into target t. Swap two characters within a row, or swap characters in one column across two rows. Output any valid construction using at most 2M operations.','先利用第一行已有字符，再从其他行补齐。按行维护字符频次，减少无效查找。',['把字符串放进 N×M 网格。','一个字符最多两次交换就能到达目标格。','先匹配第一行已有的字符，再从其他行补缺口。']),
1588:('奇妙函数',['数学规律','递推','模运算'],'挑战','array','若整数含有 0、1 以外的数字，把每位改成它的奇偶值；否则整数减 1。求重复执行到 0 的次数，答案模 1,000,000,007。整数可能长达 200,000 位。','Repeatedly transform x: if any digit is not 0 or 1, replace every digit with its parity; otherwise subtract 1. Count operations until zero, modulo 1,000,000,007. Input numbers can contain 200,000 digits.','官方通过只含 0/1 的十进制数与二进制排名的关系推导贡献，线性处理数位。递推不应一律标成通用 DP。',['先手算 210 的变化。','完成一次奇偶变换后，剩下的数字只含 0 和 1。','考虑每一位对操作次数的贡献，并及时取模。']),
1587:('让数值各不相同',['贪心','计数','模运算'],'挑战','array','数组长度 N，初值在 1..N。每次可以给一个元素加非零 K。求使所有元素互不相同的最少操作次数；K 也可能为负。','Each operation adds a fixed nonzero K to one array element. Minimize operations until all values are distinct. Initially values are in 1..N, and K may be negative.','按模 |K| 的余数分组，处理重复值；负 K 可通过变换统一处理。',['加 K 会改变余数吗？','同一位置留下一个数，其余需要继续移动。','不要遗漏负 K 和 64 位答案。']),
1565:('购买牛奶',['贪心','预处理','二进制'],'挑战','array','第 i 种套餐含 2^(i−1) 桶牛奶，价格为 aᵢ，可重复购买。每次询问至少买 x 桶的最小花费，允许多买。','Deal i contains 2^(i−1) buckets and costs aᵢ. Deals can be repeated. For each query, find the cheapest way to buy at least x buckets; buying extra is allowed.','先用两个小套餐修正更贵的大套餐，再从大到小选择，同时比较多买一个套餐的情况。',['至少 x 桶不等于恰好 x 桶。','一个大套餐会不会比两个小套餐贵？','从大到小选，并记录多买一份的候选答案。']),
1564:('Moo Hunt',['位掩码','枚举','状态压缩 DP（可选）'],'挑战','moo','N 个格子各放 M 或 O。给定 K 次点击三元组 (x,y,z)，三格依次为 MOO 就得一分。选择整个棋盘，让总分最大，并统计有多少个棋盘达到最大分。N≤20。','Choose M or O for each of N cells. Each given ordered triple scores when its cells spell MOO. Find the maximum total score and the number of boards attaining it. N is at most 20.','官方第一种满分解法是聚合相同三元组后枚举棋盘；第二种可选解法复用较小状态得分。GitHub 上另有 SOS DP 实现。',['N≤20，棋盘一共有 2^N 种。','重复出现的点击三元组能否先合并？','改变一格时，只更新涉及这一格的贡献。']),
1563:('哞声键盘 IV',['逆向思考','字符串','奇偶性'],'进阶','array','键盘只有 M 和 O。输入 O 前，所有已输入字母会 M/O 互换。判断能否得到目标串；k=1 时还要输出一种按键序列。','Typing O flips every previously typed M/O character before appending O. Decide whether a target string can be produced; when k=1, also output a valid keystroke sequence.','从末尾向前处理，用一个奇偶状态记录是否被反转。',['最后一次按键产生的字母还会被反转吗？','从右往左确定按键。','反转两次相当于没有反转。']),
1541:('牛群摄影',['二维数组','增量维护','单调性'],'挑战','grid','N×N 网格每格有一个美丽值，初始全为 0。每次增大一个格子的值，求任意 K×K 正方形内的最大总和。','All values in an N×N grid start at zero. Updates strictly increase one cell. After each update, report the largest sum over any K×K square.','只更新包含变化格子的窗口；利用数值只增不减维护全局最大值。',['一格变化会影响哪些照片？','列出包含这个格子的窗口左上角范围。','所有窗口和都不下降，无需重新扫描全部窗口。']),
1540:('COW 拆分',['构造','字符串','分类讨论'],'挑战','array','字符串由 COW、OWC、WCO 三种块拼接。每次删除一个形如 Y+Y 的子序列。判断能否清空，并按 k 的要求给出最少或至多多一次的操作方案。','The string consists of COW, OWC, and WCO blocks. Remove square subsequences Y+Y until it is empty, and construct a solution satisfying the operation bound specified by k.','官方从奇偶性和方串入手，证明可用至多两次操作构造。小数据可先枚举子序列。',['先考虑字符串总长度的奇偶性。','一次操作成功要求整个串是什么形式？','比较前后两半中对应的三个字母块。']),
1539:('筹码交换',['数学规律','分类讨论','取整'],'挑战','array','持有 A、B 两类筹码，可用 cB 枚 B 换 cA 枚 A。求最少再收到多少枚任意类型筹码，才能保证最终拥有至少 fA 枚 A。','Trade cB type-B chips for cA type-A chips. Find the minimum number of additional chips that guarantees at least fA type-A chips, regardless of the types received.','官方满分解法通过最坏分配与取模边界得到 O(1) 计算，不把第三方的二分解法误记为唯一考点。',['先判断现有筹码是否已经足够。','保证意味着对最不利的筹码分配也要成立。','寻找仍然不够的最大新增总数，再加一。']),
1493:('打印序列',['分类讨论','重复块','区间 DP（拓展）'],'挑战','printing','用 PRINT x 和可嵌套的 REP 循环输出给定序列。程序最多含 K 条 PRINT 语句，K≤3；循环次数不计入 PRINT 条数。判断是否存在这样的程序。','Generate a target sequence with PRINT commands and nested REP loops. At most K PRINT statements may occur in the program, with K≤3. Repeating a block does not add PRINT statements.','官方解法按 K 分类，检查重复块及切分点。区间 DP 是拓展视角，本版不将其标为官方唯一解法。',['区分 PRINT 语句条数和实际输出长度。','先检查整个区间能否由更短的块重复得到。','也可以把区间切成两段，组合两段所需的 PRINT 条数。']),
1492:('构造 MEX',['计数','前缀统计','贪心'],'进阶','array','每次可把数组中的一个元素改为任意非负整数。对每个 i=0..N，求让数组 MEX 恰好等于 i 的最少修改次数。MEX 是未出现的最小非负整数。','Change any array element to a nonnegative integer. For each target MEX from 0 to N, minimize changes. MEX means the smallest nonnegative integer absent from the array.','必须消除所有 i，并补齐小于 i 的缺失值；一次修改可能同时完成两件事。',['MEX=i 要满足哪两个条件？','统计 i 的出现次数和 0..i−1 的缺失种数。','一次修改能同时消除 i 并补一个缺失值。']),
1491:('镜像画布',['二维数组','对称分组','增量维护'],'进阶','reflection','偶数阶方格画布需要关于中央横轴、纵轴同时对称。给定初始画布及单格翻转，求初始时和每次翻转后最少再改多少格能恢复对称。','Restore horizontal and vertical reflection symmetry on an even-sized square canvas. Report the fewest cell changes needed initially and after every specified single-cell toggle.','每四个对称位置形成一个独立组。每次只重算受影响的那一组。',['标出一个格子的三个镜像伙伴。','四格中有 c 格涂色，统一颜色最少改多少格？','一次翻转只影响一个对称组。']),
1469:('牛群体检',['枚举','中心扩展','增量维护'],'挑战','array','选择一个连续区间反转牛群顺序。对每个匹配数量 c，统计有多少个反转区间能让恰好 c 个位置与目标品种匹配。','Reverse exactly one contiguous segment. Count, for every c, how many segment choices produce exactly c matches with the target species sequence.','围绕中心向两端扩展，只更新新交换的两个位置。官方题面明确建议满分使用 Python 以外的语言。',['先写小数据的枚举反转。','区间向两侧各扩一格时，哪些位置贡献会改变？','分别处理奇数长度与偶数长度的中心。']),
1468:('哞声序列 II',['前缀统计','集合','计数'],'进阶','array','在数组中按原顺序选出三个数，满足后两数相等且与第一个不同。统计不同的数值三元组数量，不能把重复出现的位置组合重复计数。','Count distinct value triples obtainable as subsequences, where the last two values match and differ from the first. Different index choices yielding the same triple count only once.','利用某值最右两次出现，并预处理前缀不同元素个数以去重计数。',['这里是子序列，不要求连续。','后两项相同时，可优先考虑哪两次出现？','维护前缀不同值个数，并去掉与后两项相同的值。']),
1467:('星图叠加',['网格','贪心','依赖顺序'],'挑战','grid','星星可能消失，或统一向右 A、向下 B 移动。两张照片叠加后像素为白、灰、黑，分别表示 0、1、2 张照片有星星。求初始星星最少数量，不可能则输出 −1。','Stars disappear or shift right by A and down by B. An overlay marks cells occupied in zero, one, or both photos. Find the minimum initial star count, or report impossibility.','先满足黑格的强制要求，再检查白格，按移动依赖顺序贪心处理灰格。',['黑格说明两张照片在这里都有星星。','尝试定位移动前对应的位置。','先处理强制条件，再处理有选择的灰格。']),
1445:('哞声字符串',['字符串','枚举','增量维护'],'进阶','array','字符串可能有至多一个错误字符。找出所有可能至少出现 F 次的三字母子串 abb，其中 a≠b，按字典序输出。','A string may contain one corrupted character. List all possible length-three patterns abb with a≠b that could occur at least F times after correcting at most one character.','改变一个字符只影响附近至多三个长度为三的窗口，可局部更新频次。',['先统计原串的三字符窗口。','修改一个位置会影响哪些窗口？','试探修改后还要恢复计数，才能继续枚举。']),
1444:('农场主的奶酪块',['三维坐标','计数','增量维护'],'进阶','cheese','N×N×N 奶酪立方体中，每次移除一个单位方块。每次移除后，统计可完整放入 1×1×N 长条的空通道数量，长条可沿三个坐标轴摆放。','Remove unit cubes from an N×N×N cheese block. After each removal, count empty axis-aligned channels that can hold a 1×1×N brick. Count all three orientations.','分别统计三个方向上每一条轴线被挖掉的方块数。一条线达到 N 时新增一个通道。',['长条只有沿 x、y、z 轴三种方向。','一个方块属于几条轴线？','每次只更新穿过这个方块的三条线。']),
1443:('连锁四舍五入',['数学规律','数位','预处理'],'进阶','array','比较直接舍入到某个 10 的幂与逐级连锁舍入。对每个 N，统计 2..N 中两种结果不同的整数个数。','Compare direct rounding to a power of ten with rounding successively through smaller powers. For each N, count integers from 2 through N where the results differ.','从小规模模拟找规律；满分解法统计以连续 4 开头的特殊数值区间。',['从 45、49、50、445 等数开始手算。','哪些数会因为低位进位使高位从 4 变成 5？','按数字位数统计连续的有效区间。']),
}
for p in r:
 k=p['round'];
 if k.startswith('season26'):
  num=int(re.search(r'contest(\d)',k).group(1));p['year']=2026;p['season']='2025–26';p['roundLabel']=f'2026 第 {num} 场'
 else:
  m=k[:3];y=2000+int(k[3:5]);p['year']=y;p['season']=f'{y if m=="dec" else y-1}–{str(y+1 if m=="dec" else y)[2:]}';p['roundLabel']=f'{y} / '+{'dec':'12','jan':'01','feb':'02'}[m]
 p['zhTitle']=p['title'];p['level']='未标注';p['visual']='pending';p['summary']='这道题的样例与官方入口已入库，逐题教学讲解正在补充。请先打开官方题面阅读完整要求。';p['summaryEn']='Samples and official source links are available. The teaching walkthrough is not yet written; read the official statement for complete requirements.';p['hints']=[];p['analysis']='';p['checker']='special' if p['id'] in [1589,1540,1563] else 'tokens';p['testsImported']=0;p['testsTotal']=0
 if p['id'] in C:
  zh,tags,level,visual,s,en,analysis,hints=C[p['id']];p.update(zhTitle=zh,tags=tags,level=level,visual=visual,summary=s,summaryEn=en,analysis=analysis,hints=hints,reviewStatus='已核验',reviewedAt='2026-10-02')
  p['reviewEvidence']=p['editorial']
 if p['id']==1564:p['alternativeSource']='https://github.com/ZhaLuc/USACO/blob/main/bronze/02_moo_hunt.cpp'
 t=root/f"public/tests/{p['id']}.json"
 if t.exists():
  t=json.loads(t.read_text());p['testsImported']=t['imported'];p['testsTotal']=t['officialTotal']
 if p['id']==1469:p['languageNote']='官方提示：建议使用 Python 之外的语言争取满分。'
(root/'data/catalog.json').write_text(json.dumps(r,ensure_ascii=False,indent=2))
print('catalog',len(r),'reviewed',sum(p['reviewStatus']=='已核验' for p in r))
